### ISSUE TITLE
Error while parsing drops

### ISSUE THREAD

**Issue by Lorrainrm** [happyzleaf/PixelmonPlaceholders#4]
Ello!

Got an error when /papi p Eisenbahnn %pokedex_Magikarp_drops_main%

 Error occurred while executing command 'papi p Eisenbahnn %pokedex_Magikarp_drops_main%' for source EntityPlayerMP['Eisenbahnn'/177, l='world', x=3611.66, y=92.55, z=4838.38]: tried to access field net.minecraft.item.ItemStack.field_77994_a from class com.github.happyzleaf.pixelmonplaceholders.utility.ParserUtility
java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemStack.field_77994_a from class com.github.happyzleaf.pixelmonplaceholders.utility.ParserUtility
	at com.github.happyzleaf.pixelmonplaceholders.utility.ParserUtility.getItemStackInfo(ParserUtility.java:310) ~[ParserUtility.class:?]
	at com.github.happyzleaf.pixelmonplaceholders.utility.ParserUtility.parsePokedexInfo(ParserUtility.java:256) ~[ParserUtility.class:?]
	at com.github.happyzleaf.pixelmonplaceholders.Placeholders.pokedex(Placeholders.java:215) ~[Placeholders.class:?]
	at me.rojo8399.placeholderapi.placeholder.pokedexPlaceholder_Placeholders_pokedex12.parse(Unknown Source) ~[?:?]
	at me.rojo8399.placeholderapi.placeholder.pokedexPlaceholder_Placeholders_pokedex12.parse(Unknown Source) ~[?:?]
	at me.rojo8399.placeholderapi.impl.placeholder.ExpansionBuilderImpl$1.parse(ExpansionBuilderImpl.java:253) ~[ExpansionBuilderImpl$1.class:?]
	at me.rojo8399.placeholderapi.impl.placeholder.Store.parse(Store.java:324) ~[Store.class:?]
	at me.rojo8399.placeholderapi.impl.placeholder.Store.parse(Store.java:335) ~[Store.class:?]
	at me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl.rpt(PlaceholderServiceImpl.java:277) ~[PlaceholderServiceImpl.class:?]
	at me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl.fillPlaceholders(PlaceholderServiceImpl.java:93) ~[PlaceholderServiceImpl.class:?]
	at me.rojo8399.placeholderapi.impl.PlaceholderServiceImpl.replacePlaceholders(PlaceholderServiceImpl.java:220) ~[PlaceholderServiceImpl.class:?]
	at me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(PlaceholderService.java:315) ~[PlaceholderService.class:?]
	at me.rojo8399.placeholderapi.PlaceholderService.replacePlaceholders(PlaceholderService.java:288) ~[PlaceholderService.class:?]
	at me.rojo8399.placeholderapi.impl.commands.ParseCommand.execute(ParseCommand.java:49) ~[ParseCommand.class:?]
	at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2586-7.1.0-BETA-2867]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2586-7.1.0-BETA-2867]
	at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2586-7.1.0-BETA-2867]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:322) [SpongeCommandManager.class:1.12.2-2586-7.1.0-BETA-2867]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2586-7.1.0-BETA-2867]
	at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkn000(SourceFile:539) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:275) [SpongeImplHooks.class:1.12.2-2586-7.1.0-BETA-2867]
	at net.minecraft.server.MinecraftServer.redirect$onRun$zjc000(MinecraftServer.java:4007) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**Comment by Lorrainrm** [comment]
zpixelmonplaceholders-1.2.2_1

PlaceholderAPI-4.4

**Comment by hqppyz** [comment]
Pixelmon version?

**Comment by Lorrainrm** [comment]
Was at 6.1 back on them ^

Still same issue at 6.2.1 latest server patch.

**Comment by hqppyz** [comment]
This is an issue probably with your java environment, but i'm going to delete any use of reflection in the next release so it won't be a problem :)

**Comment by Lorrainrm** [comment]
Alright. Does it work for you?

**Comment by hqppyz** [comment]
Yeah, indeed

**Comment by hqppyz** [comment]
I've did some investigation, you'll get rid of this problem with the next update, probably, even tho i haven't done anything special to fix that

**Comment by Lorrainrm** [comment]
Awesome!

**Comment by hqppyz** [comment]
Please go and try the latest release and tell me if that fixed your problem

**Comment by Lorrainrm** [comment]
Looking fine :)
Does it get from the database or from the json files? Like if i change something in a drop for a certain poke, will it return what is in the json?

**Comment by hqppyz** [comment]
I'm getting all the variables through a generic class, i'm pretty it's where pixelmon gets its values too, so if it's not coded in a very weird way it should reflect the jsons changes as well
Btw close this thread when you're ready :)

**Comment by hqppyz** [comment]
Oh god when am i goong to learn this website?
